#!/bin/bash

job=Football
user=hongqi
token=b3923d9729b371fad60d46a8d3dbac44
url="http://127.0.0.1:8080"
#curl -O http://hongqi:b3923d9729b371fad60d46a8d3dbac44@127.0.0.1:8080/jnlpJars/jenkins-cli.jar
java -jar jenkins-cli.jar -s ${url} -auth ${user}:${token} declarative-linter < Jenkinsfile
echo "************************"
curl --user ${user}:${token} -X POST -F "jenkinsfile=<Jenkinsfile" ${url}/pipeline-model-converter/validate
exit 1;
